name: 'Insert Project Tree'
description: 'Automatically setting up project tree text to README.md'
author: 'smoothbear'
inputs:
    regex:
      description: 'text to be replaced.'
      default: '{%project-tree%}'
      required: false
    path:
      description: 'file to be replaced text.'
      default: 'README.md'
      required: false
    message:
      description: 'commit message when text updated.'
      default: 'update: project tree'
      required: false
    email:
      description: 'to be committed user email.'
      required: true
    username:
      description: 'to be committed user name.'
      required: true
runs:
    using: 'node16'
    main: 'dist/project/index.js'
