name: Update to README

on:
  push:
    branches: [ "main" ]

jobs:
  change-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Insert Project Tree
        uses: smoothbear/project-tree-action@0.0.5
        with:
          email: ${{ secrets.GIT_EMAIL }}
          username: smoothbear
