name: Update to README

on:
  push:
    branches: [ "main" ]

jobs:
  change-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Insert Project Tree
        uses: smoothbear/project-tree-action@0.0.1
        with:
          email: ${{ secrets.GIT_EMAIL }}
          name: smoothbear
